version: 2.1 

jobs:
  build1:
    docker:
      image: "circleci/node:12"

    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-packages-{{ checksum "yarn.lock" }}
      - run: 
          command: "yarn global add node-gyp && yarn install"
          name: "installation"
      - save_cache:
          key: yarn-v1-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules