version: 2.1 

commands:
    restore_cache_cmd:
      steps:
        - restore_cache:
            key: yarn-v1-packages-{{ checksum "yarn.lock" }}
    save_cache_cmd:
      steps:
        - save_cache:
            paths:
              - ./node_modules
            key: yarn-v1-packages-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      - image: "circleci/node:12"

    steps:
      - checkout
      - restore_cache_cmd
      - run: 
          command: "yarn global add node-gyp && yarn install"
          name: "installation"
      - save_cache_cmd
