version: 2.1 

orbs:
  win: circleci/windows@2.2.0

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
        key:
          npm-v1-dependencies-{{ checksum "yarn.lock" }}
  save_cache_cmd:
    steps:
      - save_cache:
        paths:
          - ~/.m2
        key: npm-v1-dependencies-{{ checksum "yarn.lock" }}


jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:

      - checkout
      - restore_cache_cmd
      - run: yarn global add node-gyp && yarn install
      - save_cache_cmd